// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_SOCBar;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_escudo_copy_png);    // assets\ESCUDO copy.png
LV_IMG_DECLARE(ui_img_imcard2_png);    // assets\ImCard2.png

LV_FONT_DECLARE(ui_font_OxaBold40);
LV_FONT_DECLARE(ui_font_SuiGen22);
LV_FONT_DECLARE(ui_font_SuiGen24);
LV_FONT_DECLARE(ui_font_SuiGen40);
LV_FONT_DECLARE(ui_font_SuiGen40Ext);
LV_FONT_DECLARE(ui_font_SuiGen55);
LV_FONT_DECLARE(ui_font_SuiGen90);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
