// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_TextHTemp;
lv_obj_t * ui_HighTemp;
lv_obj_t * ui_SOCBar;
lv_obj_t * ui_Divisoria;
lv_obj_t * ui_Divisoria2;
lv_obj_t * ui_DivisoriaSup;
lv_obj_t * ui_TextZeroPercent;
lv_obj_t * ui_TextHalfPercent;
lv_obj_t * ui_TextOneHundredPercent;
lv_obj_t * ui_TextLTemp;
lv_obj_t * ui_LowTemp;
lv_obj_t * ui_TextLVolt;
lv_obj_t * ui_TextHVolt;
lv_obj_t * ui_TextPackVolt;
lv_obj_t * ui_PackVoltage;
lv_obj_t * ui_HighVoltage;
lv_obj_t * ui_LowVoltage;
lv_obj_t * ui_LogoFormula;
lv_obj_t * ui_TextPackCurrent;
lv_obj_t * ui_PackCurrent;
lv_obj_t * ui_CardSD;
lv_obj_t * ui_BordaSD1;
lv_obj_t * ui_BordaSD2;
lv_obj_t * ui_BordaSD3;
lv_obj_t * ui_BordaSD4;
lv_obj_t * ui_BordaSD5;
lv_obj_t * ui_SOC;
lv_obj_t * ui_TextSpeed;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_cardsd[1] = {&ui_img_cardsd2_png};
const lv_img_dsc_t * ui_imgset_imcard[1] = {&ui_img_imcard2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
