// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextHTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TextHTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextHTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextHTemp, -265);
    lv_obj_set_y(ui_TextHTemp, 70);
    lv_obj_set_align(ui_TextHTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextHTemp, "HIGH TEMP");
    lv_obj_set_style_text_color(ui_TextHTemp, lv_color_hex(0x00AEED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextHTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TextHTemp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TextHTemp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextHTemp, &ui_font_SuiGeneris22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HighTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_HighTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HighTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HighTemp, -265);
    lv_obj_set_y(ui_HighTemp, 110);
    lv_obj_set_align(ui_HighTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HighTemp, "30°C");
    lv_obj_set_style_text_color(ui_HighTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HighTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HighTemp, &ui_font_SuiGeneris40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOCBar = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_SOCBar, 25, LV_ANIM_OFF);
    lv_obj_set_width(ui_SOCBar, 800);
    lv_obj_set_height(ui_SOCBar, 80);
    lv_obj_set_x(ui_SOCBar, 0);
    lv_obj_set_y(ui_SOCBar, -145);
    lv_obj_set_align(ui_SOCBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SOCBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SOCBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SOCBar, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SOCBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SOCBar, lv_color_hex(0xB10404), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SOCBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SOCBar, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SOCBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SOCBar, 150, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SOCBar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SOCBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SOCBar, 30, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Divisoria = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Divisoria, 400);
    lv_obj_set_height(ui_Divisoria, 10);
    lv_obj_set_x(ui_Divisoria, 200);
    lv_obj_set_y(ui_Divisoria, -100);
    lv_obj_set_align(ui_Divisoria, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Divisoria, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Divisoria, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Divisoria, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Divisoria, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Divisoria, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Divisoria, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Divisoria, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Divisoria, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Divisoria, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Divisoria, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Divisoria, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Divisoria, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Divisoria, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Divisoria2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Divisoria2, 400);
    lv_obj_set_height(ui_Divisoria2, 10);
    lv_obj_set_x(ui_Divisoria2, -200);
    lv_obj_set_y(ui_Divisoria2, -100);
    lv_obj_set_align(ui_Divisoria2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Divisoria2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Divisoria2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Divisoria2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Divisoria2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Divisoria2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Divisoria2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Divisoria2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Divisoria2, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Divisoria2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Divisoria2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Divisoria2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Divisoria2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Divisoria2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Divisoria2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Divisoria2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DivisoriaSup = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_DivisoriaSup, 800);
    lv_obj_set_height(ui_DivisoriaSup, 10);
    lv_obj_set_x(ui_DivisoriaSup, 0);
    lv_obj_set_y(ui_DivisoriaSup, -190);
    lv_obj_set_align(ui_DivisoriaSup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DivisoriaSup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DivisoriaSup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_DivisoriaSup, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_DivisoriaSup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_DivisoriaSup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_DivisoriaSup, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_DivisoriaSup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_DivisoriaSup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_DivisoriaSup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextZeroPercent = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TextZeroPercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextZeroPercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_TextZeroPercent, -220);
    lv_obj_set_x(ui_TextZeroPercent, lv_pct(-25));
    lv_obj_set_align(ui_TextZeroPercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextZeroPercent, "0");
    lv_obj_set_style_text_color(ui_TextZeroPercent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextZeroPercent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextZeroPercent, &ui_font_OxaniumBold40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextHalfPercent = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TextHalfPercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextHalfPercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextHalfPercent, 0);
    lv_obj_set_y(ui_TextHalfPercent, -220);
    lv_obj_set_align(ui_TextHalfPercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextHalfPercent, "50");
    lv_obj_set_style_text_color(ui_TextHalfPercent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextHalfPercent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextHalfPercent, &ui_font_OxaniumBold40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextOneHundredPercent = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TextOneHundredPercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextOneHundredPercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_TextOneHundredPercent, -220);
    lv_obj_set_x(ui_TextOneHundredPercent, lv_pct(25));
    lv_obj_set_align(ui_TextOneHundredPercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextOneHundredPercent, "100");
    lv_obj_set_style_text_color(ui_TextOneHundredPercent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextOneHundredPercent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextOneHundredPercent, &ui_font_OxaniumBold40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextLTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TextLTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextLTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextLTemp, -265);
    lv_obj_set_y(ui_TextLTemp, 165);
    lv_obj_set_align(ui_TextLTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextLTemp, "LOW TEMP");
    lv_obj_set_style_text_color(ui_TextLTemp, lv_color_hex(0x00AEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextLTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TextLTemp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TextLTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TextLTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextLTemp, &ui_font_SuiGeneris22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LowTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LowTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LowTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LowTemp, -265);
    lv_obj_set_y(ui_LowTemp, 205);
    lv_obj_set_align(ui_LowTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LowTemp, "27°C");
    lv_obj_set_style_text_color(ui_LowTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LowTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LowTemp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LowTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LowTemp, &ui_font_SuiGeneris40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextLVolt = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TextLVolt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextLVolt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextLVolt, 275);
    lv_obj_set_y(ui_TextLVolt, 165);
    lv_obj_set_align(ui_TextLVolt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextLVolt, "LOW  VOLTAGE");
    lv_obj_set_style_text_color(ui_TextLVolt, lv_color_hex(0x00AEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextLVolt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextLVolt, &ui_font_SuiGeneris22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextHVolt = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TextHVolt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextHVolt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextHVolt, 275);
    lv_obj_set_y(ui_TextHVolt, 70);
    lv_obj_set_align(ui_TextHVolt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextHVolt, "HIGH VOLTAGE");
    lv_obj_set_style_text_color(ui_TextHVolt, lv_color_hex(0x00AEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextHVolt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextHVolt, &ui_font_SuiGeneris22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextPackVolt = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TextPackVolt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextPackVolt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextPackVolt, 270);
    lv_obj_set_y(ui_TextPackVolt, -55);
    lv_obj_set_align(ui_TextPackVolt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextPackVolt, "PACK VOLTAGE");
    lv_obj_set_style_text_color(ui_TextPackVolt, lv_color_hex(0x00AEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextPackVolt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextPackVolt, &ui_font_SuiGeneris24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PackVoltage = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PackVoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PackVoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PackVoltage, 275);
    lv_obj_set_y(ui_PackVoltage, 0);
    lv_obj_set_align(ui_PackVoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PackVoltage, "76.7 V");
    lv_obj_set_style_text_color(ui_PackVoltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PackVoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PackVoltage, &ui_font_SuiGeneris55extended, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HighVoltage = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_HighVoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HighVoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HighVoltage, 275);
    lv_obj_set_y(ui_HighVoltage, 110);
    lv_obj_set_align(ui_HighVoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HighVoltage, "4.27 V");
    lv_obj_set_style_text_color(ui_HighVoltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HighVoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HighVoltage, &ui_font_SuiGeneris40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LowVoltage = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LowVoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LowVoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LowVoltage, 275);
    lv_obj_set_y(ui_LowVoltage, 205);
    lv_obj_set_align(ui_LowVoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LowVoltage, "3.89 V");
    lv_obj_set_style_text_color(ui_LowVoltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LowVoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LowVoltage, &ui_font_SuiGeneris40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoFormula = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_LogoFormula, &ui_img_escudo_copy_png);
    lv_obj_set_width(ui_LogoFormula, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LogoFormula, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LogoFormula, 0);
    lv_obj_set_y(ui_LogoFormula, -50);
    lv_obj_set_align(ui_LogoFormula, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LogoFormula, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LogoFormula, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_LogoFormula, 30);
    lv_obj_set_style_img_recolor(ui_LogoFormula, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_LogoFormula, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextPackCurrent = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TextPackCurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextPackCurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextPackCurrent, -265);
    lv_obj_set_y(ui_TextPackCurrent, -55);
    lv_obj_set_align(ui_TextPackCurrent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextPackCurrent, "PACK CURRENT");
    lv_obj_set_style_text_color(ui_TextPackCurrent, lv_color_hex(0x00AEED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextPackCurrent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextPackCurrent, &ui_font_SuiGeneris24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PackCurrent = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PackCurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PackCurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PackCurrent, -265);
    lv_obj_set_y(ui_PackCurrent, 0);
    lv_obj_set_align(ui_PackCurrent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PackCurrent, "250 A");
    lv_obj_set_style_text_color(ui_PackCurrent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PackCurrent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PackCurrent, &ui_font_SuiGeneris55extended, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CardSD = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_CardSD, &ui_img_imcard2_png);
    lv_obj_set_width(ui_CardSD, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_CardSD, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_x(ui_CardSD, 4);
    lv_obj_set_y(ui_CardSD, 191);
    lv_obj_set_align(ui_CardSD, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CardSD, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CardSD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_CardSD, 900);
    lv_img_set_zoom(ui_CardSD, 50);
    lv_obj_set_style_bg_color(ui_CardSD, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CardSD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BordaSD1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_BordaSD1, 111);
    lv_obj_set_height(ui_BordaSD1, 29);
    lv_obj_set_x(ui_BordaSD1, 3);
    lv_obj_set_y(ui_BordaSD1, 139);
    lv_obj_set_align(ui_BordaSD1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BordaSD1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BordaSD1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BordaSD1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BordaSD1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BordaSD1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BordaSD2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_BordaSD2, 34);
    lv_obj_set_height(ui_BordaSD2, 100);
    lv_obj_set_x(ui_BordaSD2, -62);
    lv_obj_set_y(ui_BordaSD2, 190);
    lv_obj_set_align(ui_BordaSD2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BordaSD2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BordaSD2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BordaSD2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BordaSD2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BordaSD2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BordaSD3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_BordaSD3, 52);
    lv_obj_set_height(ui_BordaSD3, 97);
    lv_obj_set_x(ui_BordaSD3, 80);
    lv_obj_set_y(ui_BordaSD3, 197);
    lv_obj_set_align(ui_BordaSD3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BordaSD3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BordaSD3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BordaSD3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BordaSD3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BordaSD3, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BordaSD4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_BordaSD4, 140);
    lv_obj_set_height(ui_BordaSD4, 82);
    lv_obj_set_x(ui_BordaSD4, -12);
    lv_obj_set_y(ui_BordaSD4, 269);
    lv_obj_set_align(ui_BordaSD4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BordaSD4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BordaSD4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BordaSD4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BordaSD4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BordaSD4, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BordaSD5 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_BordaSD5, 100);
    lv_obj_set_height(ui_BordaSD5, 127);
    lv_obj_set_x(ui_BordaSD5, 74);
    lv_obj_set_y(ui_BordaSD5, 266);
    lv_obj_set_align(ui_BordaSD5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BordaSD5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BordaSD5, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BordaSD5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BordaSD5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BordaSD5, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SOC = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SOC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SOC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SOC, 0);
    lv_obj_set_y(ui_SOC, 80);
    lv_obj_set_align(ui_SOC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SOC, "97.5");
    lv_obj_set_style_text_color(ui_SOC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SOC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SOC, &ui_font_SuiGeneris90, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextSpeed = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TextSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextSpeed, 0);
    lv_obj_set_y(ui_TextSpeed, 10);
    lv_obj_set_align(ui_TextSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextSpeed, "SPEED");
    lv_obj_set_style_text_color(ui_TextSpeed, lv_color_hex(0x00AEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextSpeed, &ui_font_SuiGeneris24, LV_PART_MAIN | LV_STATE_DEFAULT);

}
